In [2]:
import pandas as pd

In [3]:
import quandl


In [4]:
df = quandl. get ("FINRA/FNRA_GOOGL")

df = df [["ShortVolume", "ShortExemptVolume", "TotalVolume",]]
print (df)

            ShortVolume  ShortExemptVolume  TotalVolume
Date                                                   
2014-04-03      27587.0              109.0      56737.0
2014-04-04      34752.0              354.0      62450.0
2014-04-07      18990.0              185.0      35857.0
2014-04-08      20950.0               72.0      36196.0
2014-04-09      12055.0               20.0      27047.0
2014-04-10      22256.0              347.0      40394.0
2014-04-11      18904.0              167.0      29852.0
2014-04-14      20920.0               72.0      38324.0
2014-04-15      21387.0               76.0      34867.0
2014-04-16      21589.0              120.0      37025.0
2014-04-17      33371.0                0.0      52253.0
2014-04-21      13975.0               40.0      22356.0
2014-04-22      14221.0                0.0      22918.0
2014-04-23       9800.0                0.0      14400.0
2014-04-24       7662.0               30.0      15828.0
2014-04-25      15533.0               11.0      

In [1]:
1+1

2

In [2]:
1/2


0.5

In [3]:
1/2.0

0.5

In [12]:
list1= (1,2,2,2,2,3)

In [17]:
list1.index(3)

5

In [6]:
list1[0]

1

In [11]:
list1.count(2)

1

In [25]:
s =set(list1)
mul = lambda s : s+1

In [24]:
n = lambda num : num**3 
n(4)

64

TypeError: unsupported operand type(s) for +: 'set' and 'int'

In [37]:
from random import randint as ri


In [98]:
list2 = []
for (a) in range (1,10):
    for (b) in range (1,10):
        a==ri(0,10)
        b==ri(0,10)
        list2.append((a,b))
list2

[(1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (2, 9),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (3, 7),
 (3, 8),
 (3, 9),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (4, 7),
 (4, 8),
 (4, 9),
 (5, 1),
 (5, 2),
 (5, 3),
 (5, 4),
 (5, 5),
 (5, 6),
 (5, 7),
 (5, 8),
 (5, 9),
 (6, 1),
 (6, 2),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 6),
 (6, 7),
 (6, 8),
 (6, 9),
 (7, 1),
 (7, 2),
 (7, 3),
 (7, 4),
 (7, 5),
 (7, 6),
 (7, 7),
 (7, 8),
 (7, 9),
 (8, 1),
 (8, 2),
 (8, 3),
 (8, 4),
 (8, 5),
 (8, 6),
 (8, 7),
 (8, 8),
 (8, 9),
 (9, 1),
 (9, 2),
 (9, 3),
 (9, 4),
 (9, 5),
 (9, 6),
 (9, 7),
 (9, 8),
 (9, 9)]

In [82]:
list(filter(lambda num: num%2==0, list2)) ## list out items that meet the lambda expression 

[4, 4, 6, 10, 10, 0, 0, 2, 10, 8]

In [103]:
s = "hio jou jjj "
list(s.split())

['hio', 'jou', 'jjj']

In [106]:
planet = "earth"
diameter = 12742
print ("the diamter of the planet {} is {}".format (planet, diameter))

the diamter of the planet earth is 12742


In [109]:
("user@domain.com").split("@")[1]

'domain.com'

In [180]:
s = "i love my DOG DOGDOGGOGODDOGDOG"
def dog(s):
    count= 0
    for word in s.split():
        if "dog" in s.lower():
            count+=1
    print(count)
dog(s)           

5


In [185]:
list3= ["Soup", "salad", "salt", "pepper", "Srange"]
list(filter(lambda word : word[0].lower()!="s", list3))

['pepper']

In [201]:
def ticket(speed, birtday): 
    if birtday: 
        speeding = speed -5
    else:
        speeding = speed
        
    if speeding<=60:
        return "no ticket"
    elif 60<speeding<=80:
        return "small ticket"
    else:
        return "big ticket"
    

In [202]:
ticket(67, True)

'small ticket'

## Numpy 


In [8]:
import numpy as np

In [13]:
my_list = [1,2,3,4,5,6]

In [14]:
arr = np.array(my_list)
arr

array([1, 2, 3, 4, 5, 6])

In [18]:
arr.reshape(3,2) ## tranform an array from one dimentional vector to a matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
(np.arange(0,22)).reshape(11,2)


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [59]:
np.zeros((2,4)), np.zeros(5)


(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.]]), array([0., 0., 0., 0., 0.]))

In [55]:

np.ones((2,2)), np.ones(5)

(array([[1., 1.],
        [1., 1.]]), array([1., 1., 1., 1., 1.]))

In [63]:
np.linspace(0,10,7) ## 7 equaly spaces floats within the range

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [75]:
 np.eye(6) #identity matrix, square matrix of 0 and 1 6X6



array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [84]:
np.random.randint(0,10,2) ## 2 random nubmers from 0 to 10

array([3, 2])

In [86]:
np.random.rand(5)  # 5 random equaly distributed from 0 to 1, similar to linspace, but from 0 to 1 only 



array([0.21629045, 0.94098275, 0.48360987, 0.5343739 , 0.67732959])

In [89]:
np.random.rand(5,5) # same like above, but a 5X5 matrix

array([[0.02483838, 0.19002964, 0.01629712, 0.1209968 , 0.09328501],
       [0.46951317, 0.98907665, 0.30508063, 0.43868742, 0.69052696],
       [0.2778694 , 0.78314267, 0.00983983, 0.66355287, 0.28961134],
       [0.48138857, 0.24869418, 0.68536598, 0.86804309, 0.8769666 ],
       [0.16898152, 0.41726398, 0.9423215 , 0.59826855, 0.38138818]])

In [102]:
np.random.randn(5) ## ramdon normal distribution centered around 0

array([-3.14744403,  0.63899416, -0.24769452, -0.53960312,  0.27798869])

In [100]:
np.random.randn(2,5) # ramdon normal distribution 

array([[-1.09014517,  0.09299117, -1.08762616,  0.02214307, -0.87952078],
       [ 0.54006791,  0.03670679, -0.81753255, -0.91496387,  0.92452712]])

In [125]:
(np.random.randint(0,25,10)).reshape(2,5)


array([[24, 24,  9, 16, 12],
       [13, 11, 20,  6,  9]])

In [128]:
(np.random.randint(1,25,10)).max()


21

In [121]:
(np.random.randint(1,25,10)).min()


2

In [139]:
arr = np.random.randint(0,25,10)
arr 

array([ 7, 17, 18, 11,  2, 15, 24, 15, 16, 12])

In [140]:
arr.max()

24

In [141]:
arr.argmax() ##index of max number in the array

6

In [142]:
arr.min()

2

In [143]:
arr.argmin()

4

In [144]:
arr.size

10

In [149]:
arr = arr.reshape(2,5)
arr

array([[ 7, 17, 18, 11,  2],
       [15, 24, 15, 16, 12]])

In [150]:
arr.shape

(2, 5)

In [153]:
arr.dtype

dtype('int64')

In [156]:
arr[1][1] ## just like a list 

24

In [160]:
r = np.arange(0,25)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [177]:
r[:5] ## up to and including index 5

array([0, 1, 2, 3, 4])

In [178]:
r[5:] ## from and excluding index 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [180]:
r = np.arange(0,25)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [183]:
r[0:5]= 100 ## broadcasting, change the value of the first 5 indexed to 100, note it changed the values in the array r
r

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [187]:
r_copy = r.copy() ## made a copy of the array r, now we can broadcase values in the copy without affecting the original array r 
r_copy 

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [199]:
r_copy[0:5] = np.arange(0,5)

In [200]:
r_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [191]:
r ## r still shows the changed values 

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [221]:
r_2 = (np.arange(0,45,1)).reshape(5,9)
r_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [224]:
r_2[1][2] ## grabe data from a matrix array using double braket

11

In [225]:
r_2[1,2] ## grabe data from a matrix array using a single braket (comma), this does no work for lists my_list[1][0]

11

In [226]:
r_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [230]:
r_2[:3,4:] ## cool stuff no? 

array([[ 4,  5,  6,  7,  8],
       [13, 14, 15, 16, 17],
       [22, 23, 24, 25, 26]])

In [238]:
bool_arr = r_2>30  ## name the bool array that meet the condition 

In [239]:
r_2[bool_arr] ## slice the array using the bool array that meets the condition 

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [252]:
r_2[r_2>30]  ## same result in one line of code, as if you wrote select from r_2 when r_2>30

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [266]:
r_2.any() ## if any of the values is  of them are true

True

In [22]:
r_3 = np.arange(1,51).reshape(5,10)
r_3 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [23]:
r_3[1:3,3:5]

array([[14, 15],
       [24, 25]])

In [24]:
r_3_list = r_3.tolist() ## convert an array into a list 

In [25]:
r_3



array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [28]:
r_3+r_3 # adding arrays, you can +, -, / (as long as not zero) , * 

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30,  32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98, 100]])

In [30]:
r_3*3

array([[  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [ 33,  36,  39,  42,  45,  48,  51,  54,  57,  60],
       [ 63,  66,  69,  72,  75,  78,  81,  84,  87,  90],
       [ 93,  96,  99, 102, 105, 108, 111, 114, 117, 120],
       [123, 126, 129, 132, 135, 138, 141, 144, 147, 150]])

In [33]:
r_4 = np.arange(0,50)
r_4/r_4 ## nan for fist value 

/Users/msellamia/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [35]:
1/r_4 ## or infinity inf

/Users/msellamia/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158,
       0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667,
       0.04      , 0.03846154, 0.03703704, 0.03571429, 0.03448276,
       0.03333333, 0.03225806, 0.03125   , 0.03030303, 0.02941176,
       0.02857143, 0.02777778, 0.02702703, 0.02631579, 0.02564103,
       0.025     , 0.02439024, 0.02380952, 0.02325581, 0.02272727,
       0.02222222, 0.02173913, 0.0212766 , 0.02083333, 0.02040816])

In [45]:
np.append(r_4, 70) ## add an element to an array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 70])

In [47]:
np.sqrt(r_4) ## square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ])

In [26]:
import numpy as np
r_5= np.arange(1,70,2)
r_5


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69])

In [28]:
def array_index(array_to_search, value): ## pull out the index on an element in an array 
    for i in range (0, array_to_search.size):
        if array_to_search[i]==value:
            return (i)

    return ("no index")


      
   
        

In [31]:
array_index(r_5,25)  ## formula to find the index of a value in an array

12

In [127]:
def array_index(array_to_search, value):
    for i in range (0, array_to_search.size):
        if array_to_search[i]==value:
            print (i)
        else:
            return "no index"
        
        
        

In [144]:
#exercies 

In [145]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [146]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [149]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [157]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [158]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [159]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [170]:
np.random.rand(1)

array([0.81272398])

In [173]:
np.random.randn(25)

array([ 2.14349829,  0.49350881, -0.30813131,  0.14172124,  0.37825925,
       -0.50208449,  1.61207027, -1.21577431,  0.06621232, -0.96604783,
        0.47386003,  0.19516475, -2.09549055, -1.7863974 , -1.52576686,
       -0.87724112,  0.05358041,  0.03099159,  1.6193956 ,  0.42591518,
       -0.90360751, -1.44578694,  0.80141748,  0.15424738,  1.05504723])

In [179]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [180]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [182]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [266]:
mat[2:,1:] ## fuck, use a come, it's not a list!!

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [289]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [290]:
mat


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [294]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [296]:
mat.sum()

325

In [303]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [363]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [1]:
## array of objects: 
import numpy as np

In [10]:
arr = np.arange (0,50, dtype=object)

In [11]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
      dtype=object)

In [6]:
### NLTK Tokenization 
import nltk


In [ ]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


In [9]:
text = "WASHINGTON — Petro O. Poroshenko was still the president of Ukraine earlier this year when his team sought a lifeline. With the polls showing him in clear danger of losing his re-election campaign, some of his associates, eager to hold on to their own jobs and influence, took steps that could have yielded a signal of public support from a vital ally: President Trump. Over several weeks in March, the office of Ukraine’s top prosecutor moved ahead on two investigations of intense interest to Mr. Trump. One was focused on an oligarch — previously cleared of wrongdoing by the same prosecutor — whose company employed former Vice President Joseph R. Biden Jr.’s son. The other dealt with the release by a separate Ukrainian law enforcement agency to the media of information that hurt Mr. Trump’s 2016 campaign"

In [10]:
tokenizer = nltk.tokenize.WhitespaceTokenizer()
tokenizer.tokenize(text)

['WASHINGTON',
 '—',
 'Petro',
 'O.',
 'Poroshenko',
 'was',
 'still',
 'the',
 'president',
 'of',
 'Ukraine',
 'earlier',
 'this',
 'year',
 'when',
 'his',
 'team',
 'sought',
 'a',
 'lifeline.',
 'With',
 'the',
 'polls',
 'showing',
 'him',
 'in',
 'clear',
 'danger',
 'of',
 'losing',
 'his',
 're-election',
 'campaign,',
 'some',
 'of',
 'his',
 'associates,',
 'eager',
 'to',
 'hold',
 'on',
 'to',
 'their',
 'own',
 'jobs',
 'and',
 'influence,',
 'took',
 'steps',
 'that',
 'could',
 'have',
 'yielded',
 'a',
 'signal',
 'of',
 'public',
 'support',
 'from',
 'a',
 'vital',
 'ally:',
 'President',
 'Trump.',
 'Over',
 'several',
 'weeks',
 'in',
 'March,',
 'the',
 'office',
 'of',
 'Ukraine’s',
 'top',
 'prosecutor',
 'moved',
 'ahead',
 'on',
 'two',
 'investigations',
 'of',
 'intense',
 'interest',
 'to',
 'Mr.',
 'Trump.',
 'One',
 'was',
 'focused',
 'on',
 'an',
 'oligarch',
 '—',
 'previously',
 'cleared',
 'of',
 'wrongdoing',
 'by',
 'the',
 'same',
 'prosecutor',
 

In [11]:
tokenizer = nltk.tokenize.TreebankWordTokenizer()
tokenizer.tokenize(text)

['WASHINGTON',
 '—',
 'Petro',
 'O.',
 'Poroshenko',
 'was',
 'still',
 'the',
 'president',
 'of',
 'Ukraine',
 'earlier',
 'this',
 'year',
 'when',
 'his',
 'team',
 'sought',
 'a',
 'lifeline.',
 'With',
 'the',
 'polls',
 'showing',
 'him',
 'in',
 'clear',
 'danger',
 'of',
 'losing',
 'his',
 're-election',
 'campaign',
 ',',
 'some',
 'of',
 'his',
 'associates',
 ',',
 'eager',
 'to',
 'hold',
 'on',
 'to',
 'their',
 'own',
 'jobs',
 'and',
 'influence',
 ',',
 'took',
 'steps',
 'that',
 'could',
 'have',
 'yielded',
 'a',
 'signal',
 'of',
 'public',
 'support',
 'from',
 'a',
 'vital',
 'ally',
 ':',
 'President',
 'Trump.',
 'Over',
 'several',
 'weeks',
 'in',
 'March',
 ',',
 'the',
 'office',
 'of',
 'Ukraine',
 '’',
 's',
 'top',
 'prosecutor',
 'moved',
 'ahead',
 'on',
 'two',
 'investigations',
 'of',
 'intense',
 'interest',
 'to',
 'Mr.',
 'Trump.',
 'One',
 'was',
 'focused',
 'on',
 'an',
 'oligarch',
 '—',
 'previously',
 'cleared',
 'of',
 'wrongdoing',
 'by'

In [16]:
tokenizer = nltk.tokenize.WordPunctTokenizer()
tokenizer.tokenize(text)


['WASHINGTON',
 '—',
 'Petro',
 'O',
 '.',
 'Poroshenko',
 'was',
 'still',
 'the',
 'president',
 'of',
 'Ukraine',
 'earlier',
 'this',
 'year',
 'when',
 'his',
 'team',
 'sought',
 'a',
 'lifeline',
 '.',
 'With',
 'the',
 'polls',
 'showing',
 'him',
 'in',
 'clear',
 'danger',
 'of',
 'losing',
 'his',
 're',
 '-',
 'election',
 'campaign',
 ',',
 'some',
 'of',
 'his',
 'associates',
 ',',
 'eager',
 'to',
 'hold',
 'on',
 'to',
 'their',
 'own',
 'jobs',
 'and',
 'influence',
 ',',
 'took',
 'steps',
 'that',
 'could',
 'have',
 'yielded',
 'a',
 'signal',
 'of',
 'public',
 'support',
 'from',
 'a',
 'vital',
 'ally',
 ':',
 'President',
 'Trump',
 '.',
 'Over',
 'several',
 'weeks',
 'in',
 'March',
 ',',
 'the',
 'office',
 'of',
 'Ukraine',
 '’',
 's',
 'top',
 'prosecutor',
 'moved',
 'ahead',
 'on',
 'two',
 'investigations',
 'of',
 'intense',
 'interest',
 'to',
 'Mr',
 '.',
 'Trump',
 '.',
 'One',
 'was',
 'focused',
 'on',
 'an',
 'oligarch',
 '—',
 'previously',
 'cl

In [17]:
## stemming

stemmer = nltk.stem.PorterStemmer()


In [19]:
" ".join(stemmer.stem(token) for token in tokenizer.tokenize(text))

'washington — petro O . poroshenko wa still the presid of ukrain earlier thi year when hi team sought a lifelin . with the poll show him in clear danger of lose hi re - elect campaign , some of hi associ , eager to hold on to their own job and influenc , took step that could have yield a signal of public support from a vital alli : presid trump . over sever week in march , the offic of ukrain ’ s top prosecutor move ahead on two investig of intens interest to Mr . trump . one wa focus on an oligarch — previous clear of wrongdo by the same prosecutor — whose compani employ former vice presid joseph R . biden Jr .’ s son . the other dealt with the releas by a separ ukrainian law enforc agenc to the media of inform that hurt Mr . trump ’ s 2016 campaign'

In [20]:
## Lemmatizing

In [21]:
stemmer = nltk.stem.WordNetLemmatizer()

In [22]:
" ".join(stemmer.lemmatize(token) for token in tokenizer.tokenize(text))

'WASHINGTON — Petro O . Poroshenko wa still the president of Ukraine earlier this year when his team sought a lifeline . With the poll showing him in clear danger of losing his re - election campaign , some of his associate , eager to hold on to their own job and influence , took step that could have yielded a signal of public support from a vital ally : President Trump . Over several week in March , the office of Ukraine ’ s top prosecutor moved ahead on two investigation of intense interest to Mr . Trump . One wa focused on an oligarch — previously cleared of wrongdoing by the same prosecutor — whose company employed former Vice President Joseph R . Biden Jr .’ s son . The other dealt with the release by a separate Ukrainian law enforcement agency to the medium of information that hurt Mr . Trump ’ s 2016 campaign'

In [33]:
## Pandas

In [34]:
## Series 

In [21]:
import numpy as np
import pandas as pd

In [20]:
letters = ["a","b","c"]
data = [10,20,30]
d = {}
for i in range (len(letters)): ## build a dictioary from a list 
        d[letters[i]]=data[i]
d

{'a': 10, 'b': 20, 'c': 30}

In [114]:
ser1= pd.Series(d)
ser1

a    10
b    20
c    30
dtype: int64

In [115]:
ser2=pd.Series(data, [2,4,5])
ser2

2    10
4    20
5    30
dtype: int64

In [57]:
ser1+ser2 ## adding series, nan when the values in the series do not match 

a   NaN
b   NaN
c   NaN
2   NaN
4   NaN
5   NaN
dtype: float64

In [79]:
from numpy.random import randn
import pandas as pd
              

In [80]:
np.random.seed(101) 

In [195]:
## DataFrame(a bunch of series that share the same index, like excel sheets. used to read data from csv files

df = pd.DataFrame(randn(5,4),["A","B","C","E","F"],["W","X","Y","Z"]) ## 5 rows, 4 columns and corresponding values 

In [156]:
df


W         X         Y         Z
A  1.585812  0.929658 -0.550876  0.942045
B -0.975349 -1.054851  2.165421 -1.267240
C -0.802843 -0.253479  0.090699  1.321715
E  0.794129  1.359712  0.771970  0.294217
F -1.391519  0.147486 -0.729466 -0.720110

In [157]:
df["W"] ## grabs colums values in a form of series 


A    1.585812
B   -0.975349
C   -0.802843
E    0.794129
F   -1.391519
Name: W, dtype: float64

In [136]:
df["W"]["C"] ## grapbs coordinates values, status with columsn first 

-1.029577156962552

In [122]:
type(df["W"])

pandas.core.series.Series

In [123]:
type(df)

pandas.core.frame.DataFrame

In [138]:
df.W.C ## another way of doing it, just like SQL

-1.029577156962552

In [145]:
df[["W","Z"]]

W         Z
A  0.889031 -1.076591
B -0.580383 -0.820463
C -1.029577  1.602816
E  0.185479 -1.335092
F -0.089298  0.870907

In [172]:
df["New"] = df["W"] + df["Z"] ## added a new coloum to df
df["New"]

A    2.527857
B   -2.242590
C    0.518872
E    1.088345
F   -2.111629
Name: New, dtype: float64

In [173]:
df

W         X         Y         Z       New
A  1.585812  0.929658 -0.550876  0.942045  2.527857
B -0.975349 -1.054851  2.165421 -1.267240 -2.242590
C -0.802843 -0.253479  0.090699  1.321715  0.518872
E  0.794129  1.359712  0.771970  0.294217  1.088345
F -1.391519  0.147486 -0.729466 -0.720110 -2.111629

In [174]:
 df.drop("New",axis=1) ## axis=1 to specify the column 

W         X         Y         Z
A  1.585812  0.929658 -0.550876  0.942045
B -0.975349 -1.054851  2.165421 -1.267240
C -0.802843 -0.253479  0.090699  1.321715
E  0.794129  1.359712  0.771970  0.294217
F -1.391519  0.147486 -0.729466 -0.720110

In [175]:
 df ## new not removed permantly unless you specify inplace=True

W         X         Y         Z       New
A  1.585812  0.929658 -0.550876  0.942045  2.527857
B -0.975349 -1.054851  2.165421 -1.267240 -2.242590
C -0.802843 -0.253479  0.090699  1.321715  0.518872
E  0.794129  1.359712  0.771970  0.294217  1.088345
F -1.391519  0.147486 -0.729466 -0.720110 -2.111629

In [176]:
df.drop("New",axis=1,inplace=True)

In [177]:
df

W         X         Y         Z
A  1.585812  0.929658 -0.550876  0.942045
B -0.975349 -1.054851  2.165421 -1.267240
C -0.802843 -0.253479  0.090699  1.321715
E  0.794129  1.359712  0.771970  0.294217
F -1.391519  0.147486 -0.729466 -0.720110

In [154]:
 df.drop("A") ## dopped a line, no need to specify the axis

W         X         Y         Z       New
B -0.580383  1.209027  1.201744 -0.820463 -1.400846
C -1.029577 -1.524856 -0.854860  1.602816  0.573238
E  0.185479 -0.994018 -0.131906 -1.335092 -1.149613
F -0.089298  0.698566 -1.409126  0.870907  0.781609

In [178]:
df

W         X         Y         Z
A  1.585812  0.929658 -0.550876  0.942045
B -0.975349 -1.054851  2.165421 -1.267240
C -0.802843 -0.253479  0.090699  1.321715
E  0.794129  1.359712  0.771970  0.294217
F -1.391519  0.147486 -0.729466 -0.720110

In [183]:
df.loc["A"] ## to return the values of the index, or row

W    1.585812
X    0.929658
Y   -0.550876
Z    0.942045
Name: A, dtype: float64

In [185]:
df.iloc[0] ## use iloc to return the values of index, or row

W    1.585812
X    0.929658
Y   -0.550876
Z    0.942045
Name: A, dtype: float64

In [194]:
df.loc["E":,"X":] ## grab values from the DataFrame 

X         Y         Z
E  1.359712  0.771970  0.294217
F  0.147486 -0.729466 -0.720110

In [201]:
 df > 0 ## where the bool is true

W      X      Y      Z
A  False   True   True   True
B  False  False  False   True
C   True  False   True   True
E   True   True  False  False
F  False  False  False  False

In [203]:
df[df>0] ## grab the values when the bool is true 

W         X         Y         Z
A       NaN  2.090539  1.004056  1.031916
B       NaN       NaN       NaN  0.292795
C  0.834355       NaN  0.119145  0.665715
E  0.407586  0.807843       NaN       NaN
F       NaN       NaN       NaN       NaN

In [221]:
df[df["X"]>0] ## filter value in colomn X that are > 0

W         X         Y         Z
A -0.285257  2.090539  1.004056  1.031916
E  0.407586  0.807843 -2.736464 -0.985153

In [223]:
df[df["X"]>0]["Z"] ## filter value in colomn X that are > 0 and by colom that meet the condition

A    1.031916
E   -0.985153
Name: Z, dtype: float64

In [233]:
df[(df["X"]>0) & (df["Z"]>1)] ## filter value in colomn X that are > 0 and in colom Z that are > 1, we use & instead of + or , 

W         X         Y         Z
A -0.285257  2.090539  1.004056  1.031916

In [234]:
df[(df["X"]>0) | (df["Z"]>1)] ## for or, use the pipe operator "|"

W         X         Y         Z
A -0.285257  2.090539  1.004056  1.031916
E  0.407586  0.807843 -2.736464 -0.985153

In [237]:
df.reset_index()## to reset the index to a numerical values, add inplace=True to permanantly change df

index         W         X         Y         Z
0     A -0.285257  2.090539  1.004056  1.031916
1     B -1.081118 -0.000355 -0.219882  0.292795
2     C  0.834355 -0.140432  0.119145  0.665715
3     E  0.407586  0.807843 -2.736464 -0.985153
4     F -0.155276 -1.013228 -1.087436 -2.567767

In [241]:
new = "AL BH NJ BN GH".split() ## easily create a list without adding the parantheses

In [242]:
new

['AL', 'BH', 'NJ', 'BN', 'GH']

In [245]:
df["Sates"] = new ## addeda new coloum to the df

In [244]:
df

W         X         Y         Z Sates
A -0.285257  2.090539  1.004056  1.031916    AL
B -1.081118 -0.000355 -0.219882  0.292795    BH
C  0.834355 -0.140432  0.119145  0.665715    NJ
E  0.407586  0.807843 -2.736464 -0.985153    BN
F -0.155276 -1.013228 -1.087436 -2.567767    GH

In [249]:
df.set_index("Sates") ## set states to be the index, not permanant unless I specify inplace=True 

W         X         Y         Z
Sates                                        
AL    -0.285257  2.090539  1.004056  1.031916
BH    -1.081118 -0.000355 -0.219882  0.292795
NJ     0.834355 -0.140432  0.119145  0.665715
BN     0.407586  0.807843 -2.736464 -0.985153
GH    -0.155276 -1.013228 -1.087436 -2.567767

In [248]:
df

W         X         Y         Z Sates
A -0.285257  2.090539  1.004056  1.031916    AL
B -1.081118 -0.000355 -0.219882  0.292795    BH
C  0.834355 -0.140432  0.119145  0.665715    NJ
E  0.407586  0.807843 -2.736464 -0.985153    BN
F -0.155276 -1.013228 -1.087436 -2.567767    GH