In [2]:
import pandas as pd

In [12]:
list1= (1,2,2,2,2,3)

In [17]:
list1.index(3)

5

In [6]:
list1[0]

1

In [11]:
list1.count(2)

1

In [25]:
s =set(list1)
mul = lambda s : s+1

In [24]:
n = lambda num : num**3 
n(4)

64

TypeError: unsupported operand type(s) for +: 'set' and 'int'

In [37]:
from random import randint as ri


In [98]:
list2 = []
for (a) in range (1,10):
    for (b) in range (1,10):
        a==ri(0,10)
        b==ri(0,10)
        list2.append((a,b))
list2

[(1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (2, 9),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (3, 7),
 (3, 8),
 (3, 9),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (4, 7),
 (4, 8),
 (4, 9),
 (5, 1),
 (5, 2),
 (5, 3),
 (5, 4),
 (5, 5),
 (5, 6),
 (5, 7),
 (5, 8),
 (5, 9),
 (6, 1),
 (6, 2),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 6),
 (6, 7),
 (6, 8),
 (6, 9),
 (7, 1),
 (7, 2),
 (7, 3),
 (7, 4),
 (7, 5),
 (7, 6),
 (7, 7),
 (7, 8),
 (7, 9),
 (8, 1),
 (8, 2),
 (8, 3),
 (8, 4),
 (8, 5),
 (8, 6),
 (8, 7),
 (8, 8),
 (8, 9),
 (9, 1),
 (9, 2),
 (9, 3),
 (9, 4),
 (9, 5),
 (9, 6),
 (9, 7),
 (9, 8),
 (9, 9)]

In [82]:
list(filter(lambda num: num%2==0, list2)) ## list out items that meet the lambda expression 

[4, 4, 6, 10, 10, 0, 0, 2, 10, 8]

In [103]:
s = "hio jou jjj "
list(s.split())

['hio', 'jou', 'jjj']

In [106]:
planet = "earth"
diameter = 12742
print ("the diamter of the planet {} is {}".format (planet, diameter))

the diamter of the planet earth is 12742


In [109]:
("user@domain.com").split("@")[1]

'domain.com'

In [180]:
s = "i love my DOG DOGDOGGOGODDOGDOG"
def dog(s):
    count= 0
    for word in s.split():
        if "dog" in s.lower():
            count+=1
    print(count)
dog(s)           

5


In [185]:
list3= ["Soup", "salad", "salt", "pepper", "Srange"]
list(filter(lambda word : word[0].lower()!="s", list3))

['pepper']

In [201]:
def ticket(speed, birtday): 
    if birtday: 
        speeding = speed -5
    else:
        speeding = speed
        
    if speeding<=60:
        return "no ticket"
    elif 60<speeding<=80:
        return "small ticket"
    else:
        return "big ticket"
    

In [202]:
ticket(67, True)

'small ticket'

## Numpy 


In [8]:
import numpy as np

In [13]:
my_list = [1,2,3,4,5,6]

In [14]:
arr = np.array(my_list)
arr

array([1, 2, 3, 4, 5, 6])

In [18]:
arr.reshape(3,2) ## tranform an array from one dimentional vector to a matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
(np.arange(0,22)).reshape(11,2)


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [59]:
np.zeros((2,4)), np.zeros(5)


(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.]]), array([0., 0., 0., 0., 0.]))

In [55]:

np.ones((2,2)), np.ones(5)

(array([[1., 1.],
        [1., 1.]]), array([1., 1., 1., 1., 1.]))

In [63]:
np.linspace(0,10,7) ## 7 equaly spaces floats within the range

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [75]:
 np.eye(6) #identity matrix, square matrix of 0 and 1 6X6



array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [84]:
np.random.randint(0,10,2) ## 2 random nubmers from 0 to 10

array([3, 2])

In [86]:
np.random.rand(5)  # 5 random equaly distributed from 0 to 1, similar to linspace, but from 0 to 1 only 



array([0.21629045, 0.94098275, 0.48360987, 0.5343739 , 0.67732959])

In [89]:
np.random.rand(5,5) # same like above, but a 5X5 matrix

array([[0.02483838, 0.19002964, 0.01629712, 0.1209968 , 0.09328501],
       [0.46951317, 0.98907665, 0.30508063, 0.43868742, 0.69052696],
       [0.2778694 , 0.78314267, 0.00983983, 0.66355287, 0.28961134],
       [0.48138857, 0.24869418, 0.68536598, 0.86804309, 0.8769666 ],
       [0.16898152, 0.41726398, 0.9423215 , 0.59826855, 0.38138818]])

In [33]:
np.random.randn(5) ## ramdon normal distribution centered around 0  5-by-5 matrix of normally distributed random numbers.

array([-0.52226783, -0.70483112, -0.81087247,  0.7894285 ,  1.37943036])

In [100]:
np.random.randn(2,5) # ramdon normal distribution 

array([[-1.09014517,  0.09299117, -1.08762616,  0.02214307, -0.87952078],
       [ 0.54006791,  0.03670679, -0.81753255, -0.91496387,  0.92452712]])

In [125]:
(np.random.randint(0,25,10)).reshape(2,5)


array([[24, 24,  9, 16, 12],
       [13, 11, 20,  6,  9]])

In [128]:
(np.random.randint(1,25,10)).max()


21

In [121]:
(np.random.randint(1,25,10)).min()


2

In [139]:
arr = np.random.randint(0,25,10)
arr 

array([ 7, 17, 18, 11,  2, 15, 24, 15, 16, 12])

In [140]:
arr.max()

24

In [141]:
arr.argmax() ##index of max number in the array

6

In [142]:
arr.min()

2

In [143]:
arr.argmin()

4

In [144]:
arr.size

10

In [149]:
arr = arr.reshape(2,5)
arr

array([[ 7, 17, 18, 11,  2],
       [15, 24, 15, 16, 12]])

In [150]:
arr.shape

(2, 5)

In [153]:
arr.dtype

dtype('int64')

In [156]:
arr[1][1] ## just like a list 

24

In [160]:
r = np.arange(0,25)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [177]:
r[:5] ## up to and including index 5

array([0, 1, 2, 3, 4])

In [178]:
r[5:] ## from and excluding index 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [180]:
r = np.arange(0,25)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [183]:
r[0:5]= 100 ## broadcasting, change the value of the first 5 indexed to 100, note it changed the values in the array r
r

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [187]:
r_copy = r.copy() ## made a copy of the array r, now we can broadcase values in the copy without affecting the original array r 
r_copy 

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [199]:
r_copy[0:5] = np.arange(0,5)

In [200]:
r_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [191]:
r ## r still shows the changed values 

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [221]:
r_2 = (np.arange(0,45,1)).reshape(5,9)
r_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [224]:
r_2[1][2] ## grabe data from a matrix array using double braket

11

In [225]:
r_2[1,2] ## grabe data from a matrix array using a single braket (comma), this does no work for lists my_list[1][0]

11

In [226]:
r_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [230]:
r_2[:3,4:] ## cool stuff no? 

array([[ 4,  5,  6,  7,  8],
       [13, 14, 15, 16, 17],
       [22, 23, 24, 25, 26]])

In [238]:
bool_arr = r_2>30  ## name the bool array that meet the condition 

In [239]:
r_2[bool_arr] ## slice the array using the bool array that meets the condition 

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [252]:
r_2[r_2>30]  ## same result in one line of code, as if you wrote select from r_2 when r_2>30

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [266]:
r_2.any() ## if any of the values is  of them are true

True

In [22]:
r_3 = np.arange(1,51).reshape(5,10)
r_3 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [23]:
r_3[1:3,3:5]

array([[14, 15],
       [24, 25]])

In [24]:
r_3_list = r_3.tolist() ## convert an array into a list 

In [25]:
r_3



array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [28]:
r_3+r_3 # adding arrays, you can +, -, / (as long as not zero) , * 

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30,  32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98, 100]])

In [30]:
r_3*3

array([[  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [ 33,  36,  39,  42,  45,  48,  51,  54,  57,  60],
       [ 63,  66,  69,  72,  75,  78,  81,  84,  87,  90],
       [ 93,  96,  99, 102, 105, 108, 111, 114, 117, 120],
       [123, 126, 129, 132, 135, 138, 141, 144, 147, 150]])

In [33]:
r_4 = np.arange(0,50)
r_4/r_4 ## nan for fist value 

/Users/msellamia/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [35]:
1/r_4 ## or infinity inf

/Users/msellamia/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158,
       0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667,
       0.04      , 0.03846154, 0.03703704, 0.03571429, 0.03448276,
       0.03333333, 0.03225806, 0.03125   , 0.03030303, 0.02941176,
       0.02857143, 0.02777778, 0.02702703, 0.02631579, 0.02564103,
       0.025     , 0.02439024, 0.02380952, 0.02325581, 0.02272727,
       0.02222222, 0.02173913, 0.0212766 , 0.02083333, 0.02040816])

In [45]:
np.append(r_4, 70) ## add an element to an array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 70])

In [47]:
np.sqrt(r_4) ## square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ])

In [26]:
import numpy as np
r_5= np.arange(1,70,2)
r_5


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69])

In [28]:
def array_index(array_to_search, value): ## pull out the index on an element in an array 
    for i in range (0, array_to_search.size):
        if array_to_search[i]==value:
            return (i)

    return ("no index")


      
   
        

In [31]:
array_index(r_5,25)  ## formula to find the index of a value in an array

12

In [127]:
def array_index(array_to_search, value):
    for i in range (0, array_to_search.size):
        if array_to_search[i]==value:
            print (i)
        else:
            return "no index"
        
        
        

In [144]:
#exercies 

In [145]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [146]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [149]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [157]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [158]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [159]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [170]:
np.random.rand(1)

array([0.81272398])

In [173]:
np.random.randn(25)

array([ 2.14349829,  0.49350881, -0.30813131,  0.14172124,  0.37825925,
       -0.50208449,  1.61207027, -1.21577431,  0.06621232, -0.96604783,
        0.47386003,  0.19516475, -2.09549055, -1.7863974 , -1.52576686,
       -0.87724112,  0.05358041,  0.03099159,  1.6193956 ,  0.42591518,
       -0.90360751, -1.44578694,  0.80141748,  0.15424738,  1.05504723])

In [179]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [180]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [182]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [266]:
mat[2:,1:] ## fuck, use a come, it's not a list!!

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [289]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [290]:
mat


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [294]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [296]:
mat.sum()

325

In [303]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [363]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [1]:
## array of objects: 
import numpy as np

In [10]:
arr = np.arange (0,50, dtype=object)

In [11]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
      dtype=object)

In [6]:
### NLTK Tokenization 
import nltk


In [ ]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


In [9]:
text = "WASHINGTON — Petro O. Poroshenko was still the president of Ukraine earlier this year when his team sought a lifeline. With the polls showing him in clear danger of losing his re-election campaign, some of his associates, eager to hold on to their own jobs and influence, took steps that could have yielded a signal of public support from a vital ally: President Trump. Over several weeks in March, the office of Ukraine’s top prosecutor moved ahead on two investigations of intense interest to Mr. Trump. One was focused on an oligarch — previously cleared of wrongdoing by the same prosecutor — whose company employed former Vice President Joseph R. Biden Jr.’s son. The other dealt with the release by a separate Ukrainian law enforcement agency to the media of information that hurt Mr. Trump’s 2016 campaign"

In [10]:
tokenizer = nltk.tokenize.WhitespaceTokenizer()
tokenizer.tokenize(text)

['WASHINGTON',
 '—',
 'Petro',
 'O.',
 'Poroshenko',
 'was',
 'still',
 'the',
 'president',
 'of',
 'Ukraine',
 'earlier',
 'this',
 'year',
 'when',
 'his',
 'team',
 'sought',
 'a',
 'lifeline.',
 'With',
 'the',
 'polls',
 'showing',
 'him',
 'in',
 'clear',
 'danger',
 'of',
 'losing',
 'his',
 're-election',
 'campaign,',
 'some',
 'of',
 'his',
 'associates,',
 'eager',
 'to',
 'hold',
 'on',
 'to',
 'their',
 'own',
 'jobs',
 'and',
 'influence,',
 'took',
 'steps',
 'that',
 'could',
 'have',
 'yielded',
 'a',
 'signal',
 'of',
 'public',
 'support',
 'from',
 'a',
 'vital',
 'ally:',
 'President',
 'Trump.',
 'Over',
 'several',
 'weeks',
 'in',
 'March,',
 'the',
 'office',
 'of',
 'Ukraine’s',
 'top',
 'prosecutor',
 'moved',
 'ahead',
 'on',
 'two',
 'investigations',
 'of',
 'intense',
 'interest',
 'to',
 'Mr.',
 'Trump.',
 'One',
 'was',
 'focused',
 'on',
 'an',
 'oligarch',
 '—',
 'previously',
 'cleared',
 'of',
 'wrongdoing',
 'by',
 'the',
 'same',
 'prosecutor',
 

In [11]:
tokenizer = nltk.tokenize.TreebankWordTokenizer()
tokenizer.tokenize(text)

['WASHINGTON',
 '—',
 'Petro',
 'O.',
 'Poroshenko',
 'was',
 'still',
 'the',
 'president',
 'of',
 'Ukraine',
 'earlier',
 'this',
 'year',
 'when',
 'his',
 'team',
 'sought',
 'a',
 'lifeline.',
 'With',
 'the',
 'polls',
 'showing',
 'him',
 'in',
 'clear',
 'danger',
 'of',
 'losing',
 'his',
 're-election',
 'campaign',
 ',',
 'some',
 'of',
 'his',
 'associates',
 ',',
 'eager',
 'to',
 'hold',
 'on',
 'to',
 'their',
 'own',
 'jobs',
 'and',
 'influence',
 ',',
 'took',
 'steps',
 'that',
 'could',
 'have',
 'yielded',
 'a',
 'signal',
 'of',
 'public',
 'support',
 'from',
 'a',
 'vital',
 'ally',
 ':',
 'President',
 'Trump.',
 'Over',
 'several',
 'weeks',
 'in',
 'March',
 ',',
 'the',
 'office',
 'of',
 'Ukraine',
 '’',
 's',
 'top',
 'prosecutor',
 'moved',
 'ahead',
 'on',
 'two',
 'investigations',
 'of',
 'intense',
 'interest',
 'to',
 'Mr.',
 'Trump.',
 'One',
 'was',
 'focused',
 'on',
 'an',
 'oligarch',
 '—',
 'previously',
 'cleared',
 'of',
 'wrongdoing',
 'by'

In [16]:
tokenizer = nltk.tokenize.WordPunctTokenizer()
tokenizer.tokenize(text)


['WASHINGTON',
 '—',
 'Petro',
 'O',
 '.',
 'Poroshenko',
 'was',
 'still',
 'the',
 'president',
 'of',
 'Ukraine',
 'earlier',
 'this',
 'year',
 'when',
 'his',
 'team',
 'sought',
 'a',
 'lifeline',
 '.',
 'With',
 'the',
 'polls',
 'showing',
 'him',
 'in',
 'clear',
 'danger',
 'of',
 'losing',
 'his',
 're',
 '-',
 'election',
 'campaign',
 ',',
 'some',
 'of',
 'his',
 'associates',
 ',',
 'eager',
 'to',
 'hold',
 'on',
 'to',
 'their',
 'own',
 'jobs',
 'and',
 'influence',
 ',',
 'took',
 'steps',
 'that',
 'could',
 'have',
 'yielded',
 'a',
 'signal',
 'of',
 'public',
 'support',
 'from',
 'a',
 'vital',
 'ally',
 ':',
 'President',
 'Trump',
 '.',
 'Over',
 'several',
 'weeks',
 'in',
 'March',
 ',',
 'the',
 'office',
 'of',
 'Ukraine',
 '’',
 's',
 'top',
 'prosecutor',
 'moved',
 'ahead',
 'on',
 'two',
 'investigations',
 'of',
 'intense',
 'interest',
 'to',
 'Mr',
 '.',
 'Trump',
 '.',
 'One',
 'was',
 'focused',
 'on',
 'an',
 'oligarch',
 '—',
 'previously',
 'cl

In [17]:
## stemming

stemmer = nltk.stem.PorterStemmer()


In [19]:
" ".join(stemmer.stem(token) for token in tokenizer.tokenize(text))

'washington — petro O . poroshenko wa still the presid of ukrain earlier thi year when hi team sought a lifelin . with the poll show him in clear danger of lose hi re - elect campaign , some of hi associ , eager to hold on to their own job and influenc , took step that could have yield a signal of public support from a vital alli : presid trump . over sever week in march , the offic of ukrain ’ s top prosecutor move ahead on two investig of intens interest to Mr . trump . one wa focus on an oligarch — previous clear of wrongdo by the same prosecutor — whose compani employ former vice presid joseph R . biden Jr .’ s son . the other dealt with the releas by a separ ukrainian law enforc agenc to the media of inform that hurt Mr . trump ’ s 2016 campaign'

In [20]:
## Lemmatizing

In [21]:
stemmer = nltk.stem.WordNetLemmatizer()

In [22]:
" ".join(stemmer.lemmatize(token) for token in tokenizer.tokenize(text))

'WASHINGTON — Petro O . Poroshenko wa still the president of Ukraine earlier this year when his team sought a lifeline . With the poll showing him in clear danger of losing his re - election campaign , some of his associate , eager to hold on to their own job and influence , took step that could have yielded a signal of public support from a vital ally : President Trump . Over several week in March , the office of Ukraine ’ s top prosecutor moved ahead on two investigation of intense interest to Mr . Trump . One wa focused on an oligarch — previously cleared of wrongdoing by the same prosecutor — whose company employed former Vice President Joseph R . Biden Jr .’ s son . The other dealt with the release by a separate Ukrainian law enforcement agency to the medium of information that hurt Mr . Trump ’ s 2016 campaign'

In [33]:
## Pandas

In [34]:
## Series 

In [1]:
import numpy as np
import pandas as pd

In [2]:
letters = ["a","b","c"]
data = [10,20,30]
d = {}
for i in range (len(letters)): ## build a dictioary from a list 
        d[letters[i]]=data[i]
d

{'a': 10, 'b': 20, 'c': 30}

In [3]:
ser1= pd.Series(d)
ser1

a    10
b    20
c    30
dtype: int64

In [115]:
ser2=pd.Series(data, [2,4,5])
ser2

2    10
4    20
5    30
dtype: int64

In [57]:
ser1+ser2 ## adding series, nan when the values in the series do not match 

a   NaN
b   NaN
c   NaN
2   NaN
4   NaN
5   NaN
dtype: float64

In [71]:
from numpy.random import randn
import pandas as pd
              

In [80]:
np.random.seed(101) 

In [90]:
## DataFrame(a bunch of series that share the same index, like excel sheets. used to read data from csv files

df = pd.DataFrame(randn(5,4),["A","B","C","E","F"],["W","X","Y","Z"]) ## 5 rows, 4 columns and corresponding values 

In [91]:
df


W         X         Y         Z
A  0.642004 -0.958897 -0.229701  0.882410
B  0.806865 -1.184201  1.604061  0.372874
C  1.390378  0.156855  0.555215  0.391733
E -1.065717 -0.963127 -1.193229  1.954080
F -0.472403  0.586068 -0.301780  0.832385

In [74]:
df["W"] ## grabs colums values in a form of series 


A   -0.228742
B   -1.204769
C    0.319940
E    0.858659
F   -0.007258
Name: W, dtype: float64

In [75]:
df["W"]["C"] ## grapbs coordinates values, status with columsn first 

0.31994042669524864

In [76]:
type(df["W"])

pandas.core.series.Series

In [77]:
type(df)

pandas.core.frame.DataFrame

In [78]:
df.W.C ## another way of doing it, just like SQL

0.31994042669524864

In [79]:
df[["W","Z"]]

W         Z
A -0.228742  0.862113
B -1.204769 -1.289125
C  0.319940 -0.802368
E  0.858659  2.087678
F -0.007258 -1.123236

In [92]:
df["New"] = df["W"] + df["Z"] ## added a new coloum to df, by simply added it to df
df["New"]

A    1.524414
B    1.179739
C    1.782110
E    0.888362
F    0.359982
Name: New, dtype: float64

In [93]:
df

W         X         Y         Z       New
A  0.642004 -0.958897 -0.229701  0.882410  1.524414
B  0.806865 -1.184201  1.604061  0.372874  1.179739
C  1.390378  0.156855  0.555215  0.391733  1.782110
E -1.065717 -0.963127 -1.193229  1.954080  0.888362
F -0.472403  0.586068 -0.301780  0.832385  0.359982

In [94]:
 df.drop("New",axis=1) ## axis=1 to specify the column

W         X         Y         Z
A  0.642004 -0.958897 -0.229701  0.882410
B  0.806865 -1.184201  1.604061  0.372874
C  1.390378  0.156855  0.555215  0.391733
E -1.065717 -0.963127 -1.193229  1.954080
F -0.472403  0.586068 -0.301780  0.832385

In [95]:
 df ## new not removed permantly unless you specify inplace=True

W         X         Y         Z       New
A  0.642004 -0.958897 -0.229701  0.882410  1.524414
B  0.806865 -1.184201  1.604061  0.372874  1.179739
C  1.390378  0.156855  0.555215  0.391733  1.782110
E -1.065717 -0.963127 -1.193229  1.954080  0.888362
F -0.472403  0.586068 -0.301780  0.832385  0.359982

In [96]:
df.drop("New",axis=1,inplace=True)

In [97]:
df

W         X         Y         Z
A  0.642004 -0.958897 -0.229701  0.882410
B  0.806865 -1.184201  1.604061  0.372874
C  1.390378  0.156855  0.555215  0.391733
E -1.065717 -0.963127 -1.193229  1.954080
F -0.472403  0.586068 -0.301780  0.832385

In [99]:
 df.drop("A") ## dopped a line, no need to specify the axis, unless there was coloum with the same name, then axis=0

W         X         Y         Z
B  0.806865 -1.184201  1.604061  0.372874
C  1.390378  0.156855  0.555215  0.391733
E -1.065717 -0.963127 -1.193229  1.954080
F -0.472403  0.586068 -0.301780  0.832385

In [100]:
df

W         X         Y         Z
A  0.642004 -0.958897 -0.229701  0.882410
B  0.806865 -1.184201  1.604061  0.372874
C  1.390378  0.156855  0.555215  0.391733
E -1.065717 -0.963127 -1.193229  1.954080
F -0.472403  0.586068 -0.301780  0.832385

In [105]:
df.loc["A"] ## to return the values of the index, or row, same as df["w"]

W    0.642004
X   -0.958897
Y   -0.229701
Z    0.882410
Name: A, dtype: float64

In [107]:
df.iloc[0] ## use iloc to return the values of index, or row, iloc for the hidden number of the index 

W    0.642004
X   -0.958897
Y   -0.229701
Z    0.882410
Name: A, dtype: float64

In [194]:
df.loc["E":,"X":] ## grab values from the DataFrame 

X         Y         Z
E  1.359712  0.771970  0.294217
F  0.147486 -0.729466 -0.720110

In [201]:
 df > 0 ## where the bool is true

W      X      Y      Z
A  False   True   True   True
B  False  False  False   True
C   True  False   True   True
E   True   True  False  False
F  False  False  False  False

In [203]:
df[df>0] ## grab the values when the bool is true 

W         X         Y         Z
A       NaN  2.090539  1.004056  1.031916
B       NaN       NaN       NaN  0.292795
C  0.834355       NaN  0.119145  0.665715
E  0.407586  0.807843       NaN       NaN
F       NaN       NaN       NaN       NaN

In [221]:
df[df["X"]>0] ## filter value in colomn X that are > 0

W         X         Y         Z
A -0.285257  2.090539  1.004056  1.031916
E  0.407586  0.807843 -2.736464 -0.985153

In [223]:
df[df["X"]>0]["Z"] ## filter value in colomn X that are > 0 and by colom that meet the condition

A    1.031916
E   -0.985153
Name: Z, dtype: float64

In [233]:
df[(df["X"]>0) & (df["Z"]>1)] ## filter value in colomn X that are > 0 and in colom Z that are > 1, we use & instead of + or , 

W         X         Y         Z
A -0.285257  2.090539  1.004056  1.031916

In [234]:
df[(df["X"]>0) | (df["Z"]>1)] ## for or, use the pipe operator "|"

W         X         Y         Z
A -0.285257  2.090539  1.004056  1.031916
E  0.407586  0.807843 -2.736464 -0.985153

In [237]:
df.reset_index()## to reset the index to a numerical values, add inplace=True to permanantly change df

index         W         X         Y         Z
0     A -0.285257  2.090539  1.004056  1.031916
1     B -1.081118 -0.000355 -0.219882  0.292795
2     C  0.834355 -0.140432  0.119145  0.665715
3     E  0.407586  0.807843 -2.736464 -0.985153
4     F -0.155276 -1.013228 -1.087436 -2.567767

In [96]:
new = "AL BH NJ BN GH".split() ## easily create a list without adding the parantheses

In [97]:
new

['AL', 'BH', 'NJ', 'BN', 'GH']

In [245]:
df["Sates"] = new ## addeda new coloum to the df

In [244]:
df

W         X         Y         Z Sates
A -0.285257  2.090539  1.004056  1.031916    AL
B -1.081118 -0.000355 -0.219882  0.292795    BH
C  0.834355 -0.140432  0.119145  0.665715    NJ
E  0.407586  0.807843 -2.736464 -0.985153    BN
F -0.155276 -1.013228 -1.087436 -2.567767    GH

In [95]:
df.set_index("Sates") ## set states to be the index, not permanant unless I specify inplace=True z

KeyError: 'Sates'

In [248]:
df

W         X         Y         Z Sates
A -0.285257  2.090539  1.004056  1.031916    AL
B -1.081118 -0.000355 -0.219882  0.292795    BH
C  0.834355 -0.140432  0.119145  0.665715    NJ
E  0.407586  0.807843 -2.736464 -0.985153    BN
F -0.155276 -1.013228 -1.087436 -2.567767    GH

In [85]:
data = {"age":[25, 20], "name":["Mohamed","Lauren"]} ## another way to create a DataFrame

In [86]:
lauren = pd.DataFrame(data)

In [87]:
lauren

age     name
0   25  Mohamed
1   20   Lauren

In [88]:
lauren.age.value_counts()

25    1
20    1
Name: age, dtype: int64

In [122]:
# MultiIndex DataFrame 

In [52]:
import pandas as pd
import numpy as np
from numpy.random import randn
outside = "G1 G1 G1 G2 G2 G2".split() 
inside =[1,2,3,1,2,3]
hier_index = list(zip(outside, inside)) ## used zip to create tuple pairs, list as a type 
hier_index = pd.MultiIndex.from_tuples(hier_index)  # MultiIndex DataFrame 

In [39]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [41]:
df = pd.DataFrame(randn(6,2),hier_index,["A","B"])

In [42]:
df 

A         B
G1 1  0.865421  1.566943
   2 -1.797202 -0.168735
   3  1.002557 -1.724318
G2 1  0.521441  1.398482
   2 -0.673742 -0.155775
   3 -2.276052 -0.031072

In [43]:
df.loc["G1"]

A         B
1  0.865421  1.566943
2 -1.797202 -0.168735
3  1.002557 -1.724318

In [44]:
df.loc["G1"].loc[1]

A    0.865421
B    1.566943
Name: 1, dtype: float64

In [45]:
df.index.names ## check the name of the indexes 

FrozenList([None, None])

In [46]:
df.index.names = ["Groups", "Num"] # rename the indexes 

In [47]:
df

A         B
Groups Num                    
G1     1    0.865421  1.566943
       2   -1.797202 -0.168735
       3    1.002557 -1.724318
G2     1    0.521441  1.398482
       2   -0.673742 -0.155775
       3   -2.276052 -0.031072

In [48]:
df.loc["G2"].loc[2]["B"] ## looking for value using rows(loc["rowname"])

-0.15577453480039566

In [49]:
df["B"]["G2"][2] ## looking for value using colums (["columnname"])

-0.15577453480039566

In [53]:
df.xs("G1") ## to filter out cross section 

A         B
Num                    
1    0.865421  1.566943
2   -1.797202 -0.168735
3    1.002557 -1.724318

In [60]:
df.xs("G1")

A         B
Num                    
1    0.865421  1.566943
2   -1.797202 -0.168735
3    1.002557 -1.724318

In [65]:
df.loc['G1'].loc[1], df.loc['G2'].loc[1]

(A    0.865421
 B    1.566943
 Name: 1, dtype: float64, A    0.521441
 B    1.398482
 Name: 1, dtype: float64)

In [70]:
df.xs(1, level="Num") ## easier way to do it, Grab Num 1 for both G1 and G2, this the only way to use Multiindex df 

A         B
Groups                    
G1      0.865421  1.566943
G2      0.521441  1.398482

In [75]:
df.isnull().sum() ## To grabe all  blank/ nill values in df, in this example, there is none

A    0
B    0
dtype: int64

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6 entries, (G1, 1) to (G2, 3)
Data columns (total 2 columns):
A    6 non-null float64
B    6 non-null float64
dtypes: float64(2)
memory usage: 415.0+ bytes


In [85]:
## Missing Data

In [86]:
import pandas as pd
import numpy as np
d = {"A":[1,2, np.nan], "B":[5,np.nan, np.nan], "C":[1,2,3]}

In [92]:
df = pd.DataFrame(d)


In [93]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [101]:
df.isnull().sum() ## number of blank values per column  A, B, C, sum(axis=1) for rows 

A    1
B    2
C    0
dtype: int64

In [110]:
df.dropna() ## to drop rows with any null values per axis=0 (columns), 

A    B  C
0  1.0  5.0  1

In [112]:
df.dropna(axis=1) ## drop columns with null values 

C
0  1
1  2
2  3

In [123]:
df.dropna(thresh=2) ## drop all rwos with 2 or more non-null values 

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [131]:
df.fillna (value="momo") ## fill missing values  with number 1 or text momo, you can skip value

A     B  C
0     1     5  1
1     2  momo  2
2  momo  momo  3

In [146]:
df["A"].fillna(value=df["A"].mean()) ## filled missing values in A with mean of column A, or median(), or std(), or mode() 

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [1]:
import pandas as pd
import numpy as np 


In [6]:
data = np.arange(20).reshape(5,4)

In [12]:
df = pd.DataFrame(data, ("A B C D F").split(), ("W X Y Z").split())

In [13]:
df

W   X   Y   Z
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15
F  16  17  18  19

In [14]:
## Group by 

In [37]:
data  = {"Company":["Goole", "FB", "MST","Goole", "FB", "MST"], "Person":["Lauren", "Moahamed", "Ben", "Lauren", "Moahamed", "Ben"], "Sales":[100, 200, 300, 400, 500, 600]}

In [39]:
df = pd.DataFrame(data) 

In [59]:
df

Company    Person  Sales
0   Goole    Lauren    100
1      FB  Moahamed    200
2     MST       Ben    300
3   Goole    Lauren    400
4      FB  Moahamed    500
5     MST       Ben    600

In [63]:
df.groupby("Person").sum() ## group by column name, and choose the output: .mean(), std(), sum()

Sales
Person         
Ben         900
Lauren      500
Moahamed    700

In [64]:
df.groupby("Person").sum().loc["Ben"] ## to grab the output 

Sales    900
Name: Ben, dtype: int64

In [67]:
df.groupby("Person").count() ## count the number of instances by column 

Company    6
Person     6
Sales      6
dtype: int64

In [71]:
df.count() ## count for each column 

Company    6
Person     6
Sales      6
dtype: int64

In [87]:
df.max() ## for max() and min() could be done at colum level 

Company         MST
Person     Moahamed
Sales           600
dtype: object

In [76]:
df.describe() ## could be done at colum level 

Sales
count    6.000000
mean   350.000000
std    187.082869
min    100.000000
25%    225.000000
50%    350.000000
75%    475.000000
max    600.000000

In [83]:
df.describe().transpose()  ## use transpose to mnake it easier to read

count   mean         std    min    25%    50%    75%    max
Sales    6.0  350.0  187.082869  100.0  225.0  350.0  475.0  600.0

In [21]:
# Merging / Joining 

import pandas as pd

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'], ## you can specify the index numbers 
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [20]:
df1


A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [7]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [8]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [24]:
#concatenation 

In [36]:
pd.concat([df1,df2,df3]) ## glue dataframes together based on the index numbers, axis=1 to concatenate columns

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [35]:
# merge 
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [39]:
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [40]:
right 

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [45]:
pd.merge(left, right, on="key") ## merge 2 dataframe based on common column, defaut is how='inner', on to spacify the key column

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [46]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [47]:
## merge on multiple keys 

In [51]:
pd.merge(left, right, on=["key1", "key2"])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [53]:
# joining : merge based on the index instead of column

In [54]:

left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [55]:
left

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [56]:
right

C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [59]:
left.join(right) ## join is used when 2 dataframes have no column in common 

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [60]:
import pandas as pd

In [64]:
print (pd.__version__)

0.23.4


In [65]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [75]:
pd.Series(mydict)

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

In [70]:
mydict

{'a': 0,
 'b': 1,
 'c': 2,
 'e': 3,
 'd': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25}

In [76]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

In [83]:
table = pd.DataFrame(ser)

In [90]:
table = table.reset_index()
table

index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

In [161]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [163]:
ser1[~ser1.not'

0    1
1    2
2    3
dtype: int64

In [164]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [165]:
ser = pd.Series(np.random.normal(10, 5, 25))

In [177]:
import numpy as np

In [186]:
np.percentile(ser, q=[0,25, 50, 75, 100])

array([ 1.07841486,  7.69619142,  9.86694583, 13.92213534, 20.72522811])

In [191]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

In [1]:
ser.unique()value_counts()

SyntaxError: invalid syntax (<ipython-input-1-8be6d5c96463>, line 1)

In [37]:
import pandas as pd

from numpy.random import rand

In [50]:
df = pd.DataFrame(randn(2,2), columns = ["A", "B" ], index=["Mo", "lo"])

In [51]:
df

A         B
Mo  0.412557  0.900999
lo -1.284911  1.994032

In [52]:
#operations 

In [90]:

import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [91]:
df["col2"].unique() 

array([444, 555, 666])

In [92]:
df["col2"].nunique() ## nunique() returns the number of unique values, similar to len()

3

In [100]:
df["col2"].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [117]:
df[(df["col1"]>2) & (df["col2"]==444)] ## user parentheses to combine 2 conditions 

col1  col2 col3
3     4   444  xyz

In [118]:
## apply a function on a df 

In [119]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [120]:
def double(x):
    return x*2

In [122]:
df.apply(double) ## use apply to apply a function on the values in df

col1  col2    col3
0     2   888  abcabc
1     4  1110  defdef
2     6  1332  ghighi
3     8   888  xyzxyz

In [126]:
df.loc[1].apply(double) ## on a row

col1         4
col2      1110
col3    defdef
Name: 1, dtype: object

In [133]:
df[["col1","col2"]].apply(double) ## on a column or 2

col1  col2
0     2   888
1     4  1110
2     6  1332
3     8   888

In [140]:
df.apply(len) ## apply len, type

col1    4
col2    4
col3    4
dtype: int64

In [144]:
df.apply(lambda x : x*2) ## same thing using lambda expression 

col1  col2    col3
0     2   888  abcabc
1     4  1110  defdef
2     6  1332  ghighi
3     8   888  xyzxyz

In [149]:
df.drop(columns = "col1")

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [158]:
df.columns ## return the columns 

Index(['col1', 'col2', 'col3'], dtype='object')

In [159]:
df.index ## range index

RangeIndex(start=0, stop=4, step=1)

In [168]:
df.sort_values("col2") ## sort values by the number of the column, index does not change 

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [178]:
df.isnull(False).sum()

TypeError: isnull() takes 1 positional argument but 2 were given

In [16]:
import numpy as np 
import pandas as pd

data = list(map(lambda x : x **2, np.arange(50).reshape(5,10)))


In [17]:
df = pd.DataFrame(data)

In [18]:
df

0     1     2     3     4     5     6     7     8     9
0     0     1     4     9    16    25    36    49    64    81
1   100   121   144   169   196   225   256   289   324   361
2   400   441   484   529   576   625   676   729   784   841
3   900   961  1024  1089  1156  1225  1296  1369  1444  1521
4  1600  1681  1764  1849  1936  2025  2116  2209  2304  2401

In [4]:
import requests
import bs4
import string
import pandas as pd
def datarabia():
    output = []
    pager=1
    while pager<=10:
        page = requests.get("https://www.datarabia.com/biz/searchOrgs.do?id=0&sectorid=0&more=1&submit=Search&orgname=&listid=&type=0&d-49489-p="+str(pager))
        soup = bs4.BeautifulSoup(page.text, "lxml")
        match = soup.find(class_="table").findAll("a")
        size = len(match)
        i=0
        while i <size:
            output.append(match[i].getText())
            i+=1
        pager+=1
    return output

In [6]:
df = pd.DataFrame (datarabia())


0
0                                                  
1                                                  
2                                                  
3                                                  
4                                                  
5             Al Aziziah Panda United Inc. (Branch)
6         Council of Political and Security Affairs
7         Council of Political and Security Affairs
8               Ministry of Culture and Information
9       Ministry of Petroleum and Mineral Resources
10       National Company for Cooperative Insurance
11              100 Hour Tailor for Gents Tailoring
12                                          1000 RT
13                              1000 Sateen Tailors
14                             101 Contracting Est.
15                                      101 Laundry
16                                  117 Barber Shop
17                                120 Cars Workshop
18                 12011404 Sportation Company Ltd.
19                                       123 Farooj
20                       13 Center For Car Services
21                    13th Center for Cars Services
22                                       1st Barber
23                              1st Computer Center
24                                            2 X 1
25                                       200 Tailor
26                           2000 Automatic Laundry
27                                      2000 Barber
28                                 2000 Barber Shop
29                                  2000 Barbershop
..                                              ...
120                 A Mdad Alkhlij Contracting Est.
121                         A Mdad Brother Intl Co.
122                       A Mdad Najid Trading Est.
123                             A Mdad Trading Est.
124                A Mdadat Altaga Contracting Est.
125                         A Mdha Contracting Est.
126           A Mdullah S. al-Amro Contracting Est.
127                           A-Adwa al-Mareia Est.
128                                 A-Amoodi Stores
129                           A-Basri Ladies Tailor
130                      A. A. al-Issa Trading Est.
131                    A. A. al-Quaymi Trading Est.
132                               A. A. Muqbil Est.
133                         A. A. Turki Corporation
134                    A. Abdallah al-Muhaymil Est.
135                     A. Abu Nayyan Trading Corp.
136                     A. Abu Nayyan Trading Corp.
137             A. Al Assailan Est. For Contracting
138                               A. al-Askar Trans
139                     A. al-Faris Industrial Est.
140            A. al-Jalil S. Ba-Hakim Trading Est.
141                  A. al-La Mabruk al-Safari Est.
142                     A. al-Mohawwis Trading Est.
143                       A. al-Najida Trading Est.
144                  A. al-Rishood Contracting Est.
145                   A. al-Ruways Contracting Est.
146                     A. al-Sultaihi Trading Est.
147   A. al-Ubayd Office for Authorized Translation
148                       A. al-Zuhayr Trading Est.
149   A. Alaunizaan Making House For Ladies Dresses

[150 rows x 1 columns]

In [18]:
df

0
0                                                  
1                                                  
2                                                  
3                                                  
4                                                  
5             Al Aziziah Panda United Inc. (Branch)
6         Council of Political and Security Affairs
7         Council of Political and Security Affairs
8               Ministry of Culture and Information
9       Ministry of Petroleum and Mineral Resources
10       National Company for Cooperative Insurance
11              100 Hour Tailor for Gents Tailoring
12                                          1000 RT
13                              1000 Sateen Tailors
14                             101 Contracting Est.
15                                      101 Laundry
16                                  117 Barber Shop
17                                120 Cars Workshop
18                 12011404 Sportation Company Ltd.
19                                       123 Farooj
20                       13 Center For Car Services
21                    13th Center for Cars Services
22                                       1st Barber
23                              1st Computer Center
24                                            2 X 1
25                                       200 Tailor
26                           2000 Automatic Laundry
27                                      2000 Barber
28                                 2000 Barber Shop
29                                  2000 Barbershop
..                                              ...
120                 A Mdad Alkhlij Contracting Est.
121                         A Mdad Brother Intl Co.
122                       A Mdad Najid Trading Est.
123                             A Mdad Trading Est.
124                A Mdadat Altaga Contracting Est.
125                         A Mdha Contracting Est.
126           A Mdullah S. al-Amro Contracting Est.
127                           A-Adwa al-Mareia Est.
128                                 A-Amoodi Stores
129                           A-Basri Ladies Tailor
130                      A. A. al-Issa Trading Est.
131                    A. A. al-Quaymi Trading Est.
132                               A. A. Muqbil Est.
133                         A. A. Turki Corporation
134                    A. Abdallah al-Muhaymil Est.
135                     A. Abu Nayyan Trading Corp.
136                     A. Abu Nayyan Trading Corp.
137             A. Al Assailan Est. For Contracting
138                               A. al-Askar Trans
139                     A. al-Faris Industrial Est.
140            A. al-Jalil S. Ba-Hakim Trading Est.
141                  A. al-La Mabruk al-Safari Est.
142                     A. al-Mohawwis Trading Est.
143                       A. al-Najida Trading Est.
144                  A. al-Rishood Contracting Est.
145                   A. al-Ruways Contracting Est.
146                     A. al-Sultaihi Trading Est.
147   A. al-Ubayd Office for Authorized Translation
148                       A. al-Zuhayr Trading Est.
149   A. Alaunizaan Making House For Ladies Dresses

[150 rows x 1 columns]